// ============================================================
//  Form1.Designer.cs  —  Leader (Member 3)
//  Auto-generated by Windows Forms Designer. Safe to edit in
//  Visual Studio Designer — open Form1.cs and press Shift+F7.
//
//  ╔══════════════════════════════════════════════════════════╗
//  ║  DESIGNER EDITING GUIDE                                  ║
//  ║  Only one screen panel is visible at a time in the form. ║
//  ║  To edit a specific screen in the Designer:              ║
//  ║    1. Open this file in the Properties window.           ║
//  ║    2. Select the panel you want (e.g. panelMenu).        ║
//  ║    3. Set its Visible = True temporarily.                ║
//  ║    4. Set panelWelcome.Visible = False.                  ║
//  ║    5. Make your changes, then restore Visible values.    ║
//  ╚══════════════════════════════════════════════════════════╝
// ============================================================
namespace JollibeeKiosk
{
    partial class Form1
    {
        /// <summary>Required designer variable.</summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>Clean up any resources being used.</summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            // ── Declare all controls ─────────────────────────────────────

            // Screen 1: Welcome
            this.panelWelcome    = new System.Windows.Forms.Panel();
            this.lblBeeEmoji     = new System.Windows.Forms.Label();
            this.lblBrand        = new System.Windows.Forms.Label();
            this.lblTagline      = new System.Windows.Forms.Label();
            this.lblSubtitle     = new System.Windows.Forms.Label();
            this.btnStartOrder   = new System.Windows.Forms.Button();

            // Screen 2: Order Type
            this.panelOrderType  = new System.Windows.Forms.Panel();
            this.panelOTHeader   = new System.Windows.Forms.Panel();
            this.lblOTTitle      = new System.Windows.Forms.Label();
            this.btnDineIn       = new System.Windows.Forms.Button();
            this.btnTakeOut      = new System.Windows.Forms.Button();
            this.btnOTBack       = new System.Windows.Forms.Button();

            // Screen 3: Menu
            this.panelMenu       = new System.Windows.Forms.Panel();
            this.panelMenuHeader = new System.Windows.Forms.Panel();
            this.lblMenuTitle    = new System.Windows.Forms.Label();
            this.lblMenuOrderType= new System.Windows.Forms.Label();
            this.flpMenuItems    = new System.Windows.Forms.FlowLayoutPanel();
            this.panelMenuFooter = new System.Windows.Forms.Panel();
            this.lblCartInfo     = new System.Windows.Forms.Label();
            this.btnMenuBack     = new System.Windows.Forms.Button();
            this.btnViewCart     = new System.Windows.Forms.Button();

            // Screen 4: Checkout
            this.panelCheckout   = new System.Windows.Forms.Panel();
            this.panelCOHeader   = new System.Windows.Forms.Panel();
            this.lblCOTitle      = new System.Windows.Forms.Label();
            this.lvwCart         = new System.Windows.Forms.ListView();
            this.colItemName     = new System.Windows.Forms.ColumnHeader();
            this.colItemPrice    = new System.Windows.Forms.ColumnHeader();
            this.colItemQty      = new System.Windows.Forms.ColumnHeader();
            this.colItemTotal    = new System.Windows.Forms.ColumnHeader();
            this.panelCOFooter   = new System.Windows.Forms.Panel();
            this.lblCOSubtotal   = new System.Windows.Forms.Label();
            this.btnCOBack       = new System.Windows.Forms.Button();
            this.btnApplyDiscount= new System.Windows.Forms.Button();

            // Screen 5: Discount
            this.panelDiscount   = new System.Windows.Forms.Panel();
            this.panelDCHeader   = new System.Windows.Forms.Panel();
            this.lblDCTitle      = new System.Windows.Forms.Label();
            this.panelDCBody     = new System.Windows.Forms.Panel();
            this.grpDiscountType = new System.Windows.Forms.GroupBox();
            this.rbtnNoDiscount  = new System.Windows.Forms.RadioButton();
            this.rbtnSeniorCitizen = new System.Windows.Forms.RadioButton();
            this.rbtnPWD         = new System.Windows.Forms.RadioButton();
            this.lblDiscountPreview = new System.Windows.Forms.Label();
            this.lblDCSubtotal   = new System.Windows.Forms.Label();
            this.lblDCDiscount   = new System.Windows.Forms.Label();
            this.lblDCTotal      = new System.Windows.Forms.Label();
            this.panelDCFooter   = new System.Windows.Forms.Panel();
            this.btnDCBack       = new System.Windows.Forms.Button();
            this.btnConfirmOrder = new System.Windows.Forms.Button();

            // Screen 6: Receipt
            this.panelReceipt    = new System.Windows.Forms.Panel();
            this.panelRCHeader   = new System.Windows.Forms.Panel();
            this.lblRCTitle      = new System.Windows.Forms.Label();
            this.rtbReceipt      = new System.Windows.Forms.RichTextBox();
            this.panelRCFooter   = new System.Windows.Forms.Panel();
            this.btnNewOrder     = new System.Windows.Forms.Button();

            // ── SuspendLayout (all containers) ───────────────────────────
            this.panelWelcome.SuspendLayout();
            this.panelOrderType.SuspendLayout();
            this.panelOTHeader.SuspendLayout();
            this.panelMenu.SuspendLayout();
            this.panelMenuHeader.SuspendLayout();
            this.panelMenuFooter.SuspendLayout();
            this.panelCheckout.SuspendLayout();
            this.panelCOHeader.SuspendLayout();
            this.panelCOFooter.SuspendLayout();
            this.panelDiscount.SuspendLayout();
            this.panelDCHeader.SuspendLayout();
            this.panelDCBody.SuspendLayout();
            this.grpDiscountType.SuspendLayout();
            this.panelDCFooter.SuspendLayout();
            this.panelReceipt.SuspendLayout();
            this.panelRCHeader.SuspendLayout();
            this.panelRCFooter.SuspendLayout();
            this.SuspendLayout();

            // ════════════════════════════════════════════════════════════
            //  SCREEN 1 — WELCOME
            // ════════════════════════════════════════════════════════════

            // lblBeeEmoji
            this.lblBeeEmoji.AutoSize  = false;
            this.lblBeeEmoji.Font      = new System.Drawing.Font("Segoe UI Emoji", 72F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblBeeEmoji.ForeColor = System.Drawing.Color.White;
            this.lblBeeEmoji.Location  = new System.Drawing.Point(350, 55);
            this.lblBeeEmoji.Name      = "lblBeeEmoji";
            this.lblBeeEmoji.Size      = new System.Drawing.Size(300, 115);
            this.lblBeeEmoji.TabIndex  = 0;
            this.lblBeeEmoji.Text      = "🐝";
            this.lblBeeEmoji.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;

            // lblBrand
            this.lblBrand.AutoSize  = false;
            this.lblBrand.Font      = new System.Drawing.Font("Segoe UI", 52F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblBrand.ForeColor = System.Drawing.Color.White;
            this.lblBrand.Location  = new System.Drawing.Point(100, 175);
            this.lblBrand.Name      = "lblBrand";
            this.lblBrand.Size      = new System.Drawing.Size(800, 85);
            this.lblBrand.TabIndex  = 1;
            this.lblBrand.Text      = "JOLLIBEE";
            this.lblBrand.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;

            // lblTagline
            this.lblTagline.AutoSize  = false;
            this.lblTagline.Font      = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
            this.lblTagline.ForeColor = System.Drawing.Color.FromArgb(253, 184, 19);
            this.lblTagline.Location  = new System.Drawing.Point(200, 265);
            this.lblTagline.Name      = "lblTagline";
            this.lblTagline.Size      = new System.Drawing.Size(600, 38);
            this.lblTagline.TabIndex  = 2;
            this.lblTagline.Text      = "Bida ang Sarap!";
            this.lblTagline.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;

            // lblSubtitle
            this.lblSubtitle.AutoSize  = false;
            this.lblSubtitle.Font      = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblSubtitle.ForeColor = System.Drawing.Color.FromArgb(255, 195, 175);
            this.lblSubtitle.Location  = new System.Drawing.Point(150, 308);
            this.lblSubtitle.Name      = "lblSubtitle";
            this.lblSubtitle.Size      = new System.Drawing.Size(700, 32);
            this.lblSubtitle.TabIndex  = 3;
            this.lblSubtitle.Text      = "Order your favorites, freshly made just for you.";
            this.lblSubtitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;

            // btnStartOrder
            this.btnStartOrder.BackColor                         = System.Drawing.Color.FromArgb(253, 184, 19);
            this.btnStartOrder.Cursor                            = System.Windows.Forms.Cursors.Hand;
            this.btnStartOrder.FlatStyle                         = System.Windows.Forms.FlatStyle.Flat;
            this.btnStartOrder.FlatAppearance.BorderSize         = 0;
            this.btnStartOrder.Font                              = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnStartOrder.ForeColor                         = System.Drawing.Color.FromArgb(120, 15, 5);
            this.btnStartOrder.Location                          = new System.Drawing.Point(300, 390);
            this.btnStartOrder.Name                              = "btnStartOrder";
            this.btnStartOrder.Size                              = new System.Drawing.Size(400, 88);
            this.btnStartOrder.TabIndex                          = 4;
            this.btnStartOrder.Text                              = "🛒   TAP TO ORDER";
            this.btnStartOrder.UseVisualStyleBackColor           = false;
            this.btnStartOrder.Click                             += new System.EventHandler(this.BtnStartOrder_Click);

            // panelWelcome
            this.panelWelcome.BackColor = System.Drawing.Color.FromArgb(218, 41, 28);
            this.panelWelcome.Controls.Add(this.btnStartOrder);
            this.panelWelcome.Controls.Add(this.lblSubtitle);
            this.panelWelcome.Controls.Add(this.lblTagline);
            this.panelWelcome.Controls.Add(this.lblBrand);
            this.panelWelcome.Controls.Add(this.lblBeeEmoji);
            this.panelWelcome.Location = new System.Drawing.Point(0, 0);
            this.panelWelcome.Name     = "panelWelcome";
            this.panelWelcome.Size     = new System.Drawing.Size(1000, 720);
            this.panelWelcome.TabIndex = 0;

            // ════════════════════════════════════════════════════════════
            //  SCREEN 2 — ORDER TYPE
            // ════════════════════════════════════════════════════════════

            // lblOTTitle (inside panelOTHeader)
            this.lblOTTitle.AutoSize  = false;
            this.lblOTTitle.Dock      = System.Windows.Forms.DockStyle.Fill;
            this.lblOTTitle.Font      = new System.Drawing.Font("Segoe UI", 22F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblOTTitle.ForeColor = System.Drawing.Color.White;
            this.lblOTTitle.Name      = "lblOTTitle";
            this.lblOTTitle.TabIndex  = 0;
            this.lblOTTitle.Text      = "How would you like your order?";
            this.lblOTTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;

            // panelOTHeader
            this.panelOTHeader.BackColor = System.Drawing.Color.FromArgb(218, 41, 28);
            this.panelOTHeader.Controls.Add(this.lblOTTitle);
            this.panelOTHeader.Dock    = System.Windows.Forms.DockStyle.Top;
            this.panelOTHeader.Name    = "panelOTHeader";
            this.panelOTHeader.Size    = new System.Drawing.Size(1000, 100);
            this.panelOTHeader.TabIndex = 0;

            // btnDineIn
            this.btnDineIn.BackColor                     = System.Drawing.Color.FromArgb(218, 41, 28);
            this.btnDineIn.Cursor                        = System.Windows.Forms.Cursors.Hand;
            this.btnDineIn.FlatStyle                     = System.Windows.Forms.FlatStyle.Flat;
            this.btnDineIn.FlatAppearance.BorderColor    = System.Drawing.Color.FromArgb(180, 25, 15);
            this.btnDineIn.FlatAppearance.BorderSize     = 2;
            this.btnDineIn.Font                          = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnDineIn.ForeColor                     = System.Drawing.Color.White;
            this.btnDineIn.Location                      = new System.Drawing.Point(100, 185);
            this.btnDineIn.Name                          = "btnDineIn";
            this.btnDineIn.Size                          = new System.Drawing.Size(340, 290);
            this.btnDineIn.TabIndex                      = 1;
            this.btnDineIn.Text                          = "🍽️\r\n\r\nDINE IN";
            this.btnDineIn.UseVisualStyleBackColor       = false;
            this.btnDineIn.Click                         += new System.EventHandler(this.BtnDineIn_Click);

            // btnTakeOut
            this.btnTakeOut.BackColor                    = System.Drawing.Color.FromArgb(218, 41, 28);
            this.btnTakeOut.Cursor                       = System.Windows.Forms.Cursors.Hand;
            this.btnTakeOut.FlatStyle                    = System.Windows.Forms.FlatStyle.Flat;
            this.btnTakeOut.FlatAppearance.BorderColor   = System.Drawing.Color.FromArgb(180, 25, 15);
            this.btnTakeOut.FlatAppearance.BorderSize    = 2;
            this.btnTakeOut.Font                         = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnTakeOut.ForeColor                    = System.Drawing.Color.White;
            this.btnTakeOut.Location                     = new System.Drawing.Point(560, 185);
            this.btnTakeOut.Name                         = "btnTakeOut";
            this.btnTakeOut.Size                         = new System.Drawing.Size(340, 290);
            this.btnTakeOut.TabIndex                     = 2;
            this.btnTakeOut.Text                         = "🥡\r\n\r\nTAKE OUT";
            this.btnTakeOut.UseVisualStyleBackColor      = false;
            this.btnTakeOut.Click                        += new System.EventHandler(this.BtnTakeOut_Click);

            // btnOTBack
            this.btnOTBack.Cursor              = System.Windows.Forms.Cursors.Hand;
            this.btnOTBack.FlatStyle           = System.Windows.Forms.FlatStyle.Flat;
            this.btnOTBack.Font                = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.btnOTBack.Location            = new System.Drawing.Point(30, 664);
            this.btnOTBack.Name                = "btnOTBack";
            this.btnOTBack.Size                = new System.Drawing.Size(120, 40);
            this.btnOTBack.TabIndex            = 3;
            this.btnOTBack.Text                = "← Back";
            this.btnOTBack.UseVisualStyleBackColor = true;
            this.btnOTBack.Click               += new System.EventHandler(this.BtnOTBack_Click);

            // panelOrderType
            this.panelOrderType.BackColor = System.Drawing.Color.White;
            this.panelOrderType.Controls.Add(this.btnOTBack);
            this.panelOrderType.Controls.Add(this.btnTakeOut);
            this.panelOrderType.Controls.Add(this.btnDineIn);
            this.panelOrderType.Controls.Add(this.panelOTHeader);
            this.panelOrderType.Location   = new System.Drawing.Point(0, 0);
            this.panelOrderType.Name       = "panelOrderType";
            this.panelOrderType.Size       = new System.Drawing.Size(1000, 720);
            this.panelOrderType.TabIndex   = 1;
            this.panelOrderType.Visible    = false;

            // ════════════════════════════════════════════════════════════
            //  SCREEN 3 — MENU
            // ════════════════════════════════════════════════════════════

            // lblMenuTitle
            this.lblMenuTitle.AutoSize  = false;
            this.lblMenuTitle.Font      = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblMenuTitle.ForeColor = System.Drawing.Color.White;
            this.lblMenuTitle.Location  = new System.Drawing.Point(30, 10);
            this.lblMenuTitle.Name      = "lblMenuTitle";
            this.lblMenuTitle.Size      = new System.Drawing.Size(500, 42);
            this.lblMenuTitle.TabIndex  = 0;
            this.lblMenuTitle.Text      = "SELECT YOUR MEAL";
            this.lblMenuTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;

            // lblMenuOrderType
            this.lblMenuOrderType.AutoSize  = false;
            this.lblMenuOrderType.Font      = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblMenuOrderType.ForeColor = System.Drawing.Color.FromArgb(253, 184, 19);
            this.lblMenuOrderType.Location  = new System.Drawing.Point(30, 52);
            this.lblMenuOrderType.Name      = "lblMenuOrderType";
            this.lblMenuOrderType.Size      = new System.Drawing.Size(300, 25);
            this.lblMenuOrderType.TabIndex  = 1;
            this.lblMenuOrderType.Text      = "Dine In";

            // panelMenuHeader
            this.panelMenuHeader.BackColor = System.Drawing.Color.FromArgb(218, 41, 28);
            this.panelMenuHeader.Controls.Add(this.lblMenuTitle);
            this.panelMenuHeader.Controls.Add(this.lblMenuOrderType);
            this.panelMenuHeader.Dock     = System.Windows.Forms.DockStyle.Top;
            this.panelMenuHeader.Name     = "panelMenuHeader";
            this.panelMenuHeader.Size     = new System.Drawing.Size(1000, 85);
            this.panelMenuHeader.TabIndex = 0;

            // flpMenuItems — populated dynamically by Form1.cs → LoadMenuPanel()
            this.flpMenuItems.AutoScroll = true;
            this.flpMenuItems.BackColor  = System.Drawing.Color.FromArgb(245, 245, 245);
            this.flpMenuItems.Dock       = System.Windows.Forms.DockStyle.Fill;
            this.flpMenuItems.Name       = "flpMenuItems";
            this.flpMenuItems.Padding    = new System.Windows.Forms.Padding(10);
            this.flpMenuItems.TabIndex   = 1;

            // lblCartInfo
            this.lblCartInfo.AutoSize  = false;
            this.lblCartInfo.Font      = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblCartInfo.ForeColor = System.Drawing.Color.FromArgb(218, 41, 28);
            this.lblCartInfo.Location  = new System.Drawing.Point(20, 22);
            this.lblCartInfo.Name      = "lblCartInfo";
            this.lblCartInfo.Size      = new System.Drawing.Size(440, 38);
            this.lblCartInfo.TabIndex  = 0;
            this.lblCartInfo.Text      = "0 item(s)   |   ₱0.00";
            this.lblCartInfo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;

            // btnMenuBack
            this.btnMenuBack.Cursor            = System.Windows.Forms.Cursors.Hand;
            this.btnMenuBack.FlatStyle         = System.Windows.Forms.FlatStyle.Flat;
            this.btnMenuBack.Font              = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.btnMenuBack.Location          = new System.Drawing.Point(700, 18);
            this.btnMenuBack.Name              = "btnMenuBack";
            this.btnMenuBack.Size              = new System.Drawing.Size(120, 44);
            this.btnMenuBack.TabIndex          = 1;
            this.btnMenuBack.Text              = "← Back";
            this.btnMenuBack.UseVisualStyleBackColor = true;
            this.btnMenuBack.Click             += new System.EventHandler(this.BtnMenuBack_Click);

            // btnViewCart
            this.btnViewCart.BackColor                   = System.Drawing.Color.FromArgb(218, 41, 28);
            this.btnViewCart.Cursor                      = System.Windows.Forms.Cursors.Hand;
            this.btnViewCart.FlatStyle                   = System.Windows.Forms.FlatStyle.Flat;
            this.btnViewCart.FlatAppearance.BorderSize   = 0;
            this.btnViewCart.Font                        = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnViewCart.ForeColor                   = System.Drawing.Color.White;
            this.btnViewCart.Location                    = new System.Drawing.Point(832, 18);
            this.btnViewCart.Name                        = "btnViewCart";
            this.btnViewCart.Size                        = new System.Drawing.Size(150, 44);
            this.btnViewCart.TabIndex                    = 2;
            this.btnViewCart.Text                        = "VIEW CART →";
            this.btnViewCart.UseVisualStyleBackColor     = false;
            this.btnViewCart.Click                       += new System.EventHandler(this.BtnViewCart_Click);

            // panelMenuFooter
            this.panelMenuFooter.BackColor = System.Drawing.Color.FromArgb(238, 238, 238);
            this.panelMenuFooter.Controls.Add(this.lblCartInfo);
            this.panelMenuFooter.Controls.Add(this.btnMenuBack);
            this.panelMenuFooter.Controls.Add(this.btnViewCart);
            this.panelMenuFooter.Dock     = System.Windows.Forms.DockStyle.Bottom;
            this.panelMenuFooter.Name     = "panelMenuFooter";
            this.panelMenuFooter.Size     = new System.Drawing.Size(1000, 80);
            this.panelMenuFooter.TabIndex = 2;

            // panelMenu (add Fill first, then Bottom, then Top — correct dock order)
            this.panelMenu.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.panelMenu.Controls.Add(this.flpMenuItems);    // Fill
            this.panelMenu.Controls.Add(this.panelMenuFooter); // Bottom
            this.panelMenu.Controls.Add(this.panelMenuHeader); // Top
            this.panelMenu.Location  = new System.Drawing.Point(0, 0);
            this.panelMenu.Name      = "panelMenu";
            this.panelMenu.Size      = new System.Drawing.Size(1000, 720);
            this.panelMenu.TabIndex  = 2;
            this.panelMenu.Visible   = false;

            // ════════════════════════════════════════════════════════════
            //  SCREEN 4 — CHECKOUT
            // ════════════════════════════════════════════════════════════

            // lblCOTitle
            this.lblCOTitle.AutoSize  = false;
            this.lblCOTitle.Dock      = System.Windows.Forms.DockStyle.Fill;
            this.lblCOTitle.Font      = new System.Drawing.Font("Segoe UI", 22F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblCOTitle.ForeColor = System.Drawing.Color.White;
            this.lblCOTitle.Name      = "lblCOTitle";
            this.lblCOTitle.TabIndex  = 0;
            this.lblCOTitle.Text      = "🛒  YOUR ORDER";
            this.lblCOTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;

            // panelCOHeader
            this.panelCOHeader.BackColor = System.Drawing.Color.FromArgb(218, 41, 28);
            this.panelCOHeader.Controls.Add(this.lblCOTitle);
            this.panelCOHeader.Dock    = System.Windows.Forms.DockStyle.Top;
            this.panelCOHeader.Name    = "panelCOHeader";
            this.panelCOHeader.Size    = new System.Drawing.Size(1000, 85);
            this.panelCOHeader.TabIndex = 0;

            // lvwCart
            this.lvwCart.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
                this.colItemName,
                this.colItemPrice,
                this.colItemQty,
                this.colItemTotal
            });
            this.colItemName.Text  = "Item";
            this.colItemName.Width = 440;
            this.colItemPrice.Text = "Unit Price";
            this.colItemPrice.Width= 150;
            this.colItemQty.Text   = "Qty";
            this.colItemQty.Width  = 70;
            this.colItemTotal.Text = "Total";
            this.colItemTotal.Width= 160;
            this.lvwCart.Dock                          = System.Windows.Forms.DockStyle.Fill;
            this.lvwCart.Font                          = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lvwCart.FullRowSelect                 = true;
            this.lvwCart.GridLines                     = true;
            this.lvwCart.Name                          = "lvwCart";
            this.lvwCart.TabIndex                      = 1;
            this.lvwCart.UseCompatibleStateImageBehavior = false;
            this.lvwCart.View                          = System.Windows.Forms.View.Details;

            // lblCOSubtotal
            this.lblCOSubtotal.AutoSize  = false;
            this.lblCOSubtotal.Font      = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblCOSubtotal.ForeColor = System.Drawing.Color.FromArgb(218, 41, 28);
            this.lblCOSubtotal.Location  = new System.Drawing.Point(20, 18);
            this.lblCOSubtotal.Name      = "lblCOSubtotal";
            this.lblCOSubtotal.Size      = new System.Drawing.Size(430, 46);
            this.lblCOSubtotal.TabIndex  = 0;
            this.lblCOSubtotal.Text      = "Subtotal:   ₱0.00";
            this.lblCOSubtotal.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;

            // btnCOBack
            this.btnCOBack.Cursor            = System.Windows.Forms.Cursors.Hand;
            this.btnCOBack.FlatStyle         = System.Windows.Forms.FlatStyle.Flat;
            this.btnCOBack.Font              = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.btnCOBack.Location          = new System.Drawing.Point(640, 20);
            this.btnCOBack.Name              = "btnCOBack";
            this.btnCOBack.Size              = new System.Drawing.Size(130, 44);
            this.btnCOBack.TabIndex          = 1;
            this.btnCOBack.Text              = "← Back";
            this.btnCOBack.UseVisualStyleBackColor = true;
            this.btnCOBack.Click             += new System.EventHandler(this.BtnCOBack_Click);

            // btnApplyDiscount
            this.btnApplyDiscount.BackColor                 = System.Drawing.Color.FromArgb(253, 184, 19);
            this.btnApplyDiscount.Cursor                    = System.Windows.Forms.Cursors.Hand;
            this.btnApplyDiscount.FlatStyle                 = System.Windows.Forms.FlatStyle.Flat;
            this.btnApplyDiscount.FlatAppearance.BorderSize = 0;
            this.btnApplyDiscount.Font                      = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnApplyDiscount.ForeColor                 = System.Drawing.Color.FromArgb(120, 15, 5);
            this.btnApplyDiscount.Location                  = new System.Drawing.Point(780, 18);
            this.btnApplyDiscount.Name                      = "btnApplyDiscount";
            this.btnApplyDiscount.Size                      = new System.Drawing.Size(202, 46);
            this.btnApplyDiscount.TabIndex                  = 2;
            this.btnApplyDiscount.Text                      = "APPLY DISCOUNT →";
            this.btnApplyDiscount.UseVisualStyleBackColor   = false;
            this.btnApplyDiscount.Click                     += new System.EventHandler(this.BtnApplyDiscount_Click);

            // panelCOFooter
            this.panelCOFooter.BackColor = System.Drawing.Color.FromArgb(238, 238, 238);
            this.panelCOFooter.Controls.Add(this.lblCOSubtotal);
            this.panelCOFooter.Controls.Add(this.btnCOBack);
            this.panelCOFooter.Controls.Add(this.btnApplyDiscount);
            this.panelCOFooter.Dock     = System.Windows.Forms.DockStyle.Bottom;
            this.panelCOFooter.Name     = "panelCOFooter";
            this.panelCOFooter.Size     = new System.Drawing.Size(1000, 85);
            this.panelCOFooter.TabIndex = 2;

            // panelCheckout (Fill → Bottom → Top)
            this.panelCheckout.BackColor = System.Drawing.Color.White;
            this.panelCheckout.Controls.Add(this.lvwCart);       // Fill
            this.panelCheckout.Controls.Add(this.panelCOFooter); // Bottom
            this.panelCheckout.Controls.Add(this.panelCOHeader); // Top
            this.panelCheckout.Location  = new System.Drawing.Point(0, 0);
            this.panelCheckout.Name      = "panelCheckout";
            this.panelCheckout.Size      = new System.Drawing.Size(1000, 720);
            this.panelCheckout.TabIndex  = 3;
            this.panelCheckout.Visible   = false;

            // ════════════════════════════════════════════════════════════
            //  SCREEN 5 — DISCOUNT
            // ════════════════════════════════════════════════════════════

            // lblDCTitle
            this.lblDCTitle.AutoSize  = false;
            this.lblDCTitle.Dock      = System.Windows.Forms.DockStyle.Fill;
            this.lblDCTitle.Font      = new System.Drawing.Font("Segoe UI", 22F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblDCTitle.ForeColor = System.Drawing.Color.White;
            this.lblDCTitle.Name      = "lblDCTitle";
            this.lblDCTitle.TabIndex  = 0;
            this.lblDCTitle.Text      = "🎟️  APPLY DISCOUNT";
            this.lblDCTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;

            // panelDCHeader
            this.panelDCHeader.BackColor = System.Drawing.Color.FromArgb(218, 41, 28);
            this.panelDCHeader.Controls.Add(this.lblDCTitle);
            this.panelDCHeader.Dock    = System.Windows.Forms.DockStyle.Top;
            this.panelDCHeader.Name    = "panelDCHeader";
            this.panelDCHeader.Size    = new System.Drawing.Size(1000, 85);
            this.panelDCHeader.TabIndex = 0;

            // rbtnNoDiscount
            this.rbtnNoDiscount.AutoSize = false;
            this.rbtnNoDiscount.Checked  = true;
            this.rbtnNoDiscount.Font     = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.rbtnNoDiscount.Location = new System.Drawing.Point(25, 35);
            this.rbtnNoDiscount.Name     = "rbtnNoDiscount";
            this.rbtnNoDiscount.Size     = new System.Drawing.Size(520, 46);
            this.rbtnNoDiscount.TabIndex = 0;
            this.rbtnNoDiscount.TabStop  = true;
            this.rbtnNoDiscount.Text     = "No Discount — Regular Price";
            this.rbtnNoDiscount.UseVisualStyleBackColor = true;
            this.rbtnNoDiscount.CheckedChanged += new System.EventHandler(this.DiscountOption_CheckedChanged);

            // rbtnSeniorCitizen
            this.rbtnSeniorCitizen.AutoSize = false;
            this.rbtnSeniorCitizen.Font     = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.rbtnSeniorCitizen.Location = new System.Drawing.Point(25, 96);
            this.rbtnSeniorCitizen.Name     = "rbtnSeniorCitizen";
            this.rbtnSeniorCitizen.Size     = new System.Drawing.Size(520, 46);
            this.rbtnSeniorCitizen.TabIndex = 1;
            this.rbtnSeniorCitizen.Text     = "👴  Senior Citizen  (15% discount)";
            this.rbtnSeniorCitizen.UseVisualStyleBackColor = true;
            this.rbtnSeniorCitizen.CheckedChanged += new System.EventHandler(this.DiscountOption_CheckedChanged);

            // rbtnPWD
            this.rbtnPWD.AutoSize = false;
            this.rbtnPWD.Font     = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.rbtnPWD.Location = new System.Drawing.Point(25, 157);
            this.rbtnPWD.Name     = "rbtnPWD";
            this.rbtnPWD.Size     = new System.Drawing.Size(520, 46);
            this.rbtnPWD.TabIndex = 2;
            this.rbtnPWD.Text     = "♿  PWD / Person with Disability  (15% discount)";
            this.rbtnPWD.UseVisualStyleBackColor = true;
            this.rbtnPWD.CheckedChanged += new System.EventHandler(this.DiscountOption_CheckedChanged);

            // grpDiscountType
            this.grpDiscountType.Controls.Add(this.rbtnNoDiscount);
            this.grpDiscountType.Controls.Add(this.rbtnSeniorCitizen);
            this.grpDiscountType.Controls.Add(this.rbtnPWD);
            this.grpDiscountType.Font     = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.grpDiscountType.ForeColor= System.Drawing.Color.FromArgb(218, 41, 28);
            this.grpDiscountType.Location = new System.Drawing.Point(50, 30);
            this.grpDiscountType.Name     = "grpDiscountType";
            this.grpDiscountType.Size     = new System.Drawing.Size(600, 225);
            this.grpDiscountType.TabIndex = 0;
            this.grpDiscountType.TabStop  = false;
            this.grpDiscountType.Text     = "Select Discount Type";

            // lblDiscountPreview
            this.lblDiscountPreview.AutoSize  = false;
            this.lblDiscountPreview.Font      = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
            this.lblDiscountPreview.ForeColor = System.Drawing.Color.FromArgb(100, 100, 100);
            this.lblDiscountPreview.Location  = new System.Drawing.Point(50, 268);
            this.lblDiscountPreview.Name      = "lblDiscountPreview";
            this.lblDiscountPreview.Size      = new System.Drawing.Size(700, 32);
            this.lblDiscountPreview.TabIndex  = 1;
            this.lblDiscountPreview.Text      = "No discount will be applied.";

            // lblDCSubtotal
            this.lblDCSubtotal.AutoSize  = false;
            this.lblDCSubtotal.Font      = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblDCSubtotal.ForeColor = System.Drawing.Color.FromArgb(80, 80, 80);
            this.lblDCSubtotal.Location  = new System.Drawing.Point(50, 315);
            this.lblDCSubtotal.Name      = "lblDCSubtotal";
            this.lblDCSubtotal.Size      = new System.Drawing.Size(600, 38);
            this.lblDCSubtotal.TabIndex  = 2;
            this.lblDCSubtotal.Text      = "Subtotal:        ₱0.00";

            // lblDCDiscount
            this.lblDCDiscount.AutoSize  = false;
            this.lblDCDiscount.Font      = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblDCDiscount.ForeColor = System.Drawing.Color.FromArgb(218, 41, 28);
            this.lblDCDiscount.Location  = new System.Drawing.Point(50, 358);
            this.lblDCDiscount.Name      = "lblDCDiscount";
            this.lblDCDiscount.Size      = new System.Drawing.Size(600, 38);
            this.lblDCDiscount.TabIndex  = 3;
            this.lblDCDiscount.Text      = "Discount (None):   -₱0.00";

            // lblDCTotal
            this.lblDCTotal.AutoSize  = false;
            this.lblDCTotal.Font      = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblDCTotal.ForeColor = System.Drawing.Color.FromArgb(218, 41, 28);
            this.lblDCTotal.Location  = new System.Drawing.Point(50, 408);
            this.lblDCTotal.Name      = "lblDCTotal";
            this.lblDCTotal.Size      = new System.Drawing.Size(600, 55);
            this.lblDCTotal.TabIndex  = 4;
            this.lblDCTotal.Text      = "TOTAL:           ₱0.00";

            // panelDCBody (Fill — contains the GroupBox and total labels)
            this.panelDCBody.BackColor = System.Drawing.Color.White;
            this.panelDCBody.Controls.Add(this.grpDiscountType);
            this.panelDCBody.Controls.Add(this.lblDiscountPreview);
            this.panelDCBody.Controls.Add(this.lblDCSubtotal);
            this.panelDCBody.Controls.Add(this.lblDCDiscount);
            this.panelDCBody.Controls.Add(this.lblDCTotal);
            this.panelDCBody.Dock     = System.Windows.Forms.DockStyle.Fill;
            this.panelDCBody.Name     = "panelDCBody";
            this.panelDCBody.TabIndex = 1;

            // btnDCBack
            this.btnDCBack.Cursor            = System.Windows.Forms.Cursors.Hand;
            this.btnDCBack.FlatStyle         = System.Windows.Forms.FlatStyle.Flat;
            this.btnDCBack.Font              = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.btnDCBack.Location          = new System.Drawing.Point(630, 20);
            this.btnDCBack.Name              = "btnDCBack";
            this.btnDCBack.Size              = new System.Drawing.Size(130, 44);
            this.btnDCBack.TabIndex          = 0;
            this.btnDCBack.Text              = "← Back";
            this.btnDCBack.UseVisualStyleBackColor = true;
            this.btnDCBack.Click             += new System.EventHandler(this.BtnDCBack_Click);

            // btnConfirmOrder
            this.btnConfirmOrder.BackColor                   = System.Drawing.Color.FromArgb(34, 139, 34);
            this.btnConfirmOrder.Cursor                      = System.Windows.Forms.Cursors.Hand;
            this.btnConfirmOrder.FlatStyle                   = System.Windows.Forms.FlatStyle.Flat;
            this.btnConfirmOrder.FlatAppearance.BorderSize   = 0;
            this.btnConfirmOrder.Font                        = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnConfirmOrder.ForeColor                   = System.Drawing.Color.White;
            this.btnConfirmOrder.Location                    = new System.Drawing.Point(770, 17);
            this.btnConfirmOrder.Name                        = "btnConfirmOrder";
            this.btnConfirmOrder.Size                        = new System.Drawing.Size(212, 50);
            this.btnConfirmOrder.TabIndex                    = 1;
            this.btnConfirmOrder.Text                        = "✅  CONFIRM ORDER";
            this.btnConfirmOrder.UseVisualStyleBackColor     = false;
            this.btnConfirmOrder.Click                       += new System.EventHandler(this.BtnConfirmOrder_Click);

            // panelDCFooter
            this.panelDCFooter.BackColor = System.Drawing.Color.FromArgb(238, 238, 238);
            this.panelDCFooter.Controls.Add(this.btnDCBack);
            this.panelDCFooter.Controls.Add(this.btnConfirmOrder);
            this.panelDCFooter.Dock     = System.Windows.Forms.DockStyle.Bottom;
            this.panelDCFooter.Name     = "panelDCFooter";
            this.panelDCFooter.Size     = new System.Drawing.Size(1000, 85);
            this.panelDCFooter.TabIndex = 2;

            // panelDiscount (Fill → Bottom → Top)
            this.panelDiscount.BackColor = System.Drawing.Color.White;
            this.panelDiscount.Controls.Add(this.panelDCBody);   // Fill
            this.panelDiscount.Controls.Add(this.panelDCFooter); // Bottom
            this.panelDiscount.Controls.Add(this.panelDCHeader); // Top
            this.panelDiscount.Location  = new System.Drawing.Point(0, 0);
            this.panelDiscount.Name      = "panelDiscount";
            this.panelDiscount.Size      = new System.Drawing.Size(1000, 720);
            this.panelDiscount.TabIndex  = 4;
            this.panelDiscount.Visible   = false;

            // ════════════════════════════════════════════════════════════
            //  SCREEN 6 — RECEIPT
            // ════════════════════════════════════════════════════════════

            // lblRCTitle
            this.lblRCTitle.AutoSize  = false;
            this.lblRCTitle.Dock      = System.Windows.Forms.DockStyle.Fill;
            this.lblRCTitle.Font      = new System.Drawing.Font("Segoe UI", 22F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblRCTitle.ForeColor = System.Drawing.Color.White;
            this.lblRCTitle.Name      = "lblRCTitle";
            this.lblRCTitle.TabIndex  = 0;
            this.lblRCTitle.Text      = "✅  ORDER CONFIRMED!";
            this.lblRCTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;

            // panelRCHeader
            this.panelRCHeader.BackColor = System.Drawing.Color.FromArgb(34, 139, 34);
            this.panelRCHeader.Controls.Add(this.lblRCTitle);
            this.panelRCHeader.Dock    = System.Windows.Forms.DockStyle.Top;
            this.panelRCHeader.Name    = "panelRCHeader";
            this.panelRCHeader.Size    = new System.Drawing.Size(1000, 85);
            this.panelRCHeader.TabIndex = 0;

            // rtbReceipt — filled by ReceiptService (Member 2)
            this.rtbReceipt.BackColor   = System.Drawing.Color.White;
            this.rtbReceipt.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.rtbReceipt.Dock        = System.Windows.Forms.DockStyle.Fill;
            this.rtbReceipt.Font        = new System.Drawing.Font("Courier New", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.rtbReceipt.Margin      = new System.Windows.Forms.Padding(20);
            this.rtbReceipt.Name        = "rtbReceipt";
            this.rtbReceipt.ReadOnly    = true;
            this.rtbReceipt.ScrollBars  = System.Windows.Forms.RichTextBoxScrollBars.Vertical;
            this.rtbReceipt.TabIndex    = 1;
            this.rtbReceipt.Text        = "";

            // btnNewOrder
            this.btnNewOrder.BackColor                   = System.Drawing.Color.FromArgb(218, 41, 28);
            this.btnNewOrder.Cursor                      = System.Windows.Forms.Cursors.Hand;
            this.btnNewOrder.Dock                        = System.Windows.Forms.DockStyle.Fill;
            this.btnNewOrder.FlatStyle                   = System.Windows.Forms.FlatStyle.Flat;
            this.btnNewOrder.FlatAppearance.BorderSize   = 0;
            this.btnNewOrder.Font                        = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnNewOrder.ForeColor                   = System.Drawing.Color.White;
            this.btnNewOrder.Name                        = "btnNewOrder";
            this.btnNewOrder.TabIndex                    = 0;
            this.btnNewOrder.Text                        = "🔄  START NEW ORDER";
            this.btnNewOrder.UseVisualStyleBackColor     = false;
            this.btnNewOrder.Click                       += new System.EventHandler(this.BtnNewOrder_Click);

            // panelRCFooter
            this.panelRCFooter.BackColor = System.Drawing.Color.FromArgb(218, 41, 28);
            this.panelRCFooter.Controls.Add(this.btnNewOrder);
            this.panelRCFooter.Dock     = System.Windows.Forms.DockStyle.Bottom;
            this.panelRCFooter.Name     = "panelRCFooter";
            this.panelRCFooter.Size     = new System.Drawing.Size(1000, 68);
            this.panelRCFooter.TabIndex = 2;

            // panelReceipt (Fill → Bottom → Top)
            this.panelReceipt.BackColor = System.Drawing.Color.White;
            this.panelReceipt.Controls.Add(this.rtbReceipt);     // Fill
            this.panelReceipt.Controls.Add(this.panelRCFooter);  // Bottom
            this.panelReceipt.Controls.Add(this.panelRCHeader);  // Top
            this.panelReceipt.Location  = new System.Drawing.Point(0, 0);
            this.panelReceipt.Name      = "panelReceipt";
            this.panelReceipt.Size      = new System.Drawing.Size(1000, 720);
            this.panelReceipt.TabIndex  = 5;
            this.panelReceipt.Visible   = false;

            // ════════════════════════════════════════════════════════════
            //  FORM CONFIGURATION
            // ════════════════════════════════════════════════════════════
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode       = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor           = System.Drawing.Color.White;
            this.ClientSize          = new System.Drawing.Size(1000, 720);
            // Add screens in reverse visibility order; panelWelcome ends up on top
            this.Controls.Add(this.panelReceipt);
            this.Controls.Add(this.panelDiscount);
            this.Controls.Add(this.panelCheckout);
            this.Controls.Add(this.panelMenu);
            this.Controls.Add(this.panelOrderType);
            this.Controls.Add(this.panelWelcome);
            this.FormBorderStyle     = System.Windows.Forms.FormBorderStyle.Sizable;
            this.MinimumSize         = new System.Drawing.Size(1016, 759);
            this.Name                = "Form1";
            this.StartPosition       = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text                = "🐝 Jollibee Kiosk";

            // ── ResumeLayouts ─────────────────────────────────────────────
            this.panelWelcome.ResumeLayout(false);
            this.panelOTHeader.ResumeLayout(false);
            this.panelOrderType.ResumeLayout(false);
            this.panelMenuHeader.ResumeLayout(false);
            this.panelMenuFooter.ResumeLayout(false);
            this.panelMenu.ResumeLayout(false);
            this.panelCOHeader.ResumeLayout(false);
            this.panelCOFooter.ResumeLayout(false);
            this.panelCheckout.ResumeLayout(false);
            this.panelDCHeader.ResumeLayout(false);
            this.grpDiscountType.ResumeLayout(false);
            this.panelDCBody.ResumeLayout(false);
            this.panelDCFooter.ResumeLayout(false);
            this.panelDiscount.ResumeLayout(false);
            this.panelRCHeader.ResumeLayout(false);
            this.panelRCFooter.ResumeLayout(false);
            this.panelReceipt.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion

        // ── Control declarations (required by Designer) ──────────────────

        // Screen 1: Welcome
        private System.Windows.Forms.Panel  panelWelcome;
        private System.Windows.Forms.Label  lblBeeEmoji;
        private System.Windows.Forms.Label  lblBrand;
        private System.Windows.Forms.Label  lblTagline;
        private System.Windows.Forms.Label  lblSubtitle;
        private System.Windows.Forms.Button btnStartOrder;

        // Screen 2: Order Type
        private System.Windows.Forms.Panel  panelOrderType;
        private System.Windows.Forms.Panel  panelOTHeader;
        private System.Windows.Forms.Label  lblOTTitle;
        private System.Windows.Forms.Button btnDineIn;
        private System.Windows.Forms.Button btnTakeOut;
        private System.Windows.Forms.Button btnOTBack;

        // Screen 3: Menu
        private System.Windows.Forms.Panel          panelMenu;
        private System.Windows.Forms.Panel          panelMenuHeader;
        private System.Windows.Forms.Label          lblMenuTitle;
        private System.Windows.Forms.Label          lblMenuOrderType;
        private System.Windows.Forms.FlowLayoutPanel flpMenuItems;
        private System.Windows.Forms.Panel          panelMenuFooter;
        private System.Windows.Forms.Label          lblCartInfo;
        private System.Windows.Forms.Button         btnMenuBack;
        private System.Windows.Forms.Button         btnViewCart;

        // Screen 4: Checkout
        private System.Windows.Forms.Panel        panelCheckout;
        private System.Windows.Forms.Panel        panelCOHeader;
        private System.Windows.Forms.Label        lblCOTitle;
        private System.Windows.Forms.ListView     lvwCart;
        private System.Windows.Forms.ColumnHeader colItemName;
        private System.Windows.Forms.ColumnHeader colItemPrice;
        private System.Windows.Forms.ColumnHeader colItemQty;
        private System.Windows.Forms.ColumnHeader colItemTotal;
        private System.Windows.Forms.Panel        panelCOFooter;
        private System.Windows.Forms.Label        lblCOSubtotal;
        private System.Windows.Forms.Button       btnCOBack;
        private System.Windows.Forms.Button       btnApplyDiscount;

        // Screen 5: Discount
        private System.Windows.Forms.Panel       panelDiscount;
        private System.Windows.Forms.Panel       panelDCHeader;
        private System.Windows.Forms.Label       lblDCTitle;
        private System.Windows.Forms.Panel       panelDCBody;
        private System.Windows.Forms.GroupBox    grpDiscountType;
        private System.Windows.Forms.RadioButton rbtnNoDiscount;
        private System.Windows.Forms.RadioButton rbtnSeniorCitizen;
        private System.Windows.Forms.RadioButton rbtnPWD;
        private System.Windows.Forms.Label       lblDiscountPreview;
        private System.Windows.Forms.Label       lblDCSubtotal;
        private System.Windows.Forms.Label       lblDCDiscount;
        private System.Windows.Forms.Label       lblDCTotal;
        private System.Windows.Forms.Panel       panelDCFooter;
        private System.Windows.Forms.Button      btnDCBack;
        private System.Windows.Forms.Button      btnConfirmOrder;

        // Screen 6: Receipt
        private System.Windows.Forms.Panel       panelReceipt;
        private System.Windows.Forms.Panel       panelRCHeader;
        private System.Windows.Forms.Label       lblRCTitle;
        private System.Windows.Forms.RichTextBox rtbReceipt;
        private System.Windows.Forms.Panel       panelRCFooter;
        private System.Windows.Forms.Button      btnNewOrder;
    }
}
